### ISSUE TITLE
Crash if exists "workspace id" option in RDP file

### ISSUE THREAD

**Issue by zhka** [Devolutions/MsRdpEx#105]
Application crashes if I add this line into RDP file:
`workspace id:s:test`

 Attaching full RDP file and two log files (with and without "workspace id" )
[RDP.zip](https://github.com/Devolutions/MsRdpEx/files/14625043/RDP.zip)

[log_fail.txt](https://github.com/Devolutions/MsRdpEx/files/14625032/log_fail.txt)
[log_ok.txt](https://github.com/Devolutions/MsRdpEx/files/14625033/log_ok.txt)

**Comment by zhka** [comment]
exit code is 9009
file C:\Windows\System32\wksprtPS.dll exists
The problem is reproduced on two PC with Win10 and Win11

**Comment by zhka** [comment]
same problem with line 
`remoteapplicationmode:i:1`

**Comment by awakecoding** [comment]
I don't get a crash on Windows 11 23H2, but both the "workspace id" and "remoteapplicationmode:i:1" options enable a special launching of a shared mstsc.exe process through a COM interface. the mstsc.exe process we launch with MsRdpEx.dll injected with Detours is terminated early on, leaving the shared mstsc.exe process to handle RemoteApp and workspace-related sessions. This a limitation for which we don't have a solution for Detours which requires that we can control the way the process is launched. Ideally it shouldn't crash, if you can figure out what's wrong on older versions of Windows it could be patched, but other than that, there's nothing we can do to support those options properly.
