### ISSUE TITLE
Consider supporting reconnection after sleep

### ISSUE THREAD

**Issue by raffaeler** [Devolutions/MsRdpEx#11]
An active RDP connection gets of course lost when the workstation goes "sleeping".
A soon as the PC is restored, sometimes it gets automatically connected back, most of the times the connection is broken.
I believe this is network-related because the reconnection to a local VM is almost always restored correctly.

Suggestion: consider supporting a solid reconnection to the session for any RDP session.

**Comment by awakecoding** [comment]
This is a feature exposed by the RDP ActiveX for automatic reconnections, you can configure the number of reconnect attempts, etc: https://docs.microsoft.com/en-us/windows/win32/termserv/imsrdpclientadvancedsettings2-maxreconnectattempts

**Comment by raffaeler** [comment]
So you will expose all the properties in managed code, right?

**Comment by awakecoding** [comment]
It's all exposed through the generated ActiveX interface already, but one can always improve on top of it with additional reconnection logic in the application. However, this is out of scope for the current project, where my aim is to wrap and extend the set of options, but not build a complete application on top of it. The current app is just a sample for testing, my next step is to create a Nuget package to be used in Remote Desktop Manager or other applications
