### ISSUE TITLE
Issue handling certain characters in .rdp filenames.

### ISSUE THREAD

**Issue by milolethbridge** [Devolutions/MsRdpEx#90]
I'm assuming it's to do with special characters based on the error message I received and it not returning the correct filename.

![explorer_2023-11-29_12-01-11](https://github.com/Devolutions/MsRdpEx/assets/80171999/c6d5ec85-b32b-4419-9684-4ce5f93d726d)

**Comment by awakecoding** [comment]
Windows processing of command-line arguments is very tricky, I'll test with a similar file name, I think this may have to do with escaping some parameters when passing them to the Detours version of CreateProcess. I just fixed an issue yesterday where the file path of the executable had to be within quotes to support paths with spaces.

**Comment by milolethbridge** [comment]
Thanks, works just fine renamed.

**Comment by awakecoding** [comment]
now fixed in https://github.com/Devolutions/MsRdpEx/releases/tag/v2023.11.29.0
